version: '3.3'
services:
    yabin:
        ports:
            - '3000:3000'
        image: 'yureien/yabin:latest'
        networks:
           yabin:
             ipv4_address: 172.50.0.2
        environment:
          - DATABASE_URL=postgresql://yabin:aninsanelygreatpassword@postgres:5432/yabin?schema=public
        depends_on:
          - postgres


    postgres:
        image: postgres:15-alpine
        hostname: postgres
        networks:
           yabin:
             ipv4_address: 172.50.0.3
        environment:
          - POSTGRES_USER=yabin
          - POSTGRES_PASSWORD=aninsanelygreatpassword
          - POSTGRES_DB=yabin
        volumes:
        - ./volumes/postgres:/var/lib/postgresql/data:Z
        restart: always

networks:
  yabin:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
          gateway: 172.50.0.1
